AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/LineLength:
  Max: 100
Style/ConditionalAssignment:
  Enabled: false